#include <dmainscreen.h>

void DMainScreen::PREPARE_ROAD_MAGNETS_CORNERS()
{
    PREPARE_ROAD_MAGNETS_UL();
    PREPARE_ROAD_MAGNETS_UR();
    PREPARE_ROAD_MAGNETS_DR();
    PREPARE_ROAD_MAGNETS_DL();
}

void DMainScreen::PREPARE_ROAD_MAGNETS_HORIZONTAL_SIDES()
{
    PREPARE_ROAD_MAGNETS_D();
    PREPARE_ROAD_MAGNETS_U();
 }

void DMainScreen::PREPARE_ROAD_MAGNETS_VERTICAL_SIDES()
{
    PREPARE_ROAD_MAGNETS_L();
    PREPARE_ROAD_MAGNETS_R();
}
